import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { open_sans } from "./ui/fonts";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "filtered.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`${open_sans.className} antialiased`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
